from __future__ import annotations

import shutil
from collections import defaultdict
from pathlib import Path

import yaml

from common import (
    dump_yaml,
    is_true,
    load_table,
    relative_posix_path,
    require_fk,
    require_unique,
    split_list,
)

SCRIPT_DIR = Path("/Workspace/Repos/ingestion-framework/ingestion-framework/generator")
DEFAULT_CONFIG_PATH = SCRIPT_DIR / "generator_config.yaml"


DATABRICKS_YML_HEADER_TEMPLATE = """# AUTO-GENERATED by generator/generate_bundles.py — do not edit by hand.
# This file is a single, self-contained bundle definition for the
# '{domain_name}' domain.  Configuration is sourced from Unity Catalog
# tables in {catalog}.{schema} (bundle_domains, jobs, pipelines, tables, variables).
"""


def load_config(config_path: Path | None = None) -> dict:
    """Load generator configuration from the YAML config file."""
    path = config_path or DEFAULT_CONFIG_PATH
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def load_variables(catalog: str, schema: str) -> tuple[dict, dict]:
    """Load the variables config table and return bundle variable definitions.

    Auto-discovers ``env_*`` columns (e.g. env_dev, env_prod); the suffix
    after ``env_`` becomes the target name.  Adding a new column
    (e.g. env_staging) is all that's needed to support a new environment.

    Returns:
        variables_def: {var_name: {"description": ..., "default": ...}}
            — emitted as the top-level ``variables:`` block in databricks.yml.
        target_variables: {target_name: {var_name: value}}
            — merged into the ``targets:`` block as per-target overrides.
    """
    try:
        rows = load_table(catalog, schema, "variables")
    except Exception:
        return {}, {}
    if not rows:
        return {}, {}

    # Auto-detect env_* columns (env_dev, env_prod, …)
    env_columns = sorted(k for k in rows[0] if k.startswith("env_"))
    if not env_columns:
        return {}, {}

    target_names = [col[len("env_"):] for col in env_columns]
    default_env_col = env_columns[0]  # first alphabetically → default value

    variables_def: dict[str, dict] = {}
    target_variables: dict[str, dict] = {t: {} for t in target_names}

    for row in rows:
        var_name = row["variable_name"].strip()
        if not var_name:
            continue
        description = row.get("description", "").strip()
        default_value = row.get(default_env_col, "").strip()

        var_def: dict = {}
        if description:
            var_def["description"] = description
        var_def["default"] = default_value
        variables_def[var_name] = var_def

        for col, target in zip(env_columns, target_names):
            value = row.get(col, "").strip()
            if value:
                target_variables[target][var_name] = value

    return variables_def, target_variables


def render_databricks_yml(
    domain_name: str,
    bundle_name: str,
    job_entries: dict[str, dict],
    pipeline_entries: dict[str, dict],
    bundle_root_dir: Path,
    catalog: str,
    schema: str,
    targets: dict | None = None,
    variables_def: dict | None = None,
) -> None:
    """Write the domain's self-contained databricks.yml into bundle_root_dir."""
    header = DATABRICKS_YML_HEADER_TEMPLATE.format(
        domain_name=domain_name, bundle_name=bundle_name, catalog=catalog, schema=schema,
    )
    bundle = {"bundle": {"name": bundle_name}}
    if variables_def:
        bundle["variables"] = variables_def
    bundle["resources"] = {"jobs": job_entries, "pipelines": pipeline_entries}
    if targets:
        bundle["targets"] = targets
    bundle_root_dir.mkdir(parents=True, exist_ok=True)
    (bundle_root_dir / "databricks.yml").write_text(header + dump_yaml(bundle), encoding="utf-8")


def destination_table_for(table: dict) -> str:
    return table.get("destination_table", "").strip() or table["source_table"]


def is_full_replace(table: dict) -> bool:
    """True when the tables row provides neither primary_keys nor cursor_columns.

    Without a primary key there is nothing to merge on, and without a cursor
    column there is no incremental high-water mark — so the table is ingested
    as a full snapshot instead: the destination is truncated and the whole
    source table is re-read on every run (see `render_job`, which requests a
    full refresh for these pipelines).
    """
    return not split_list(table.get("primary_keys", "")) and not split_list(table.get("cursor_columns", ""))


def _resolve_value(value: str, column: str, variable_names: set[str]) -> str:
    """Return ``${var.<column>}`` if *column* is a known bundle variable, else *value*."""
    if variable_names and column in variable_names:
        return f"${{var.{column}}}"
    return value


def table_object_entry(table: dict, variable_names: set[str] | None = None) -> dict:
    vn = variable_names or set()
    table_spec = {
        "destination_catalog": _resolve_value(table["target_catalog"], "target_catalog", vn),
        "destination_schema": _resolve_value(table["bronze_raw_schema"], "bronze_raw_schema", vn),
        "destination_table": destination_table_for(table),
        "source_catalog": _resolve_value(table["source_catalog"], "source_catalog", vn),
        "source_schema": table["source_schema"],
        "source_table": table["source_table"],
    }
    if is_full_replace(table):
        # Full-replace: no merge keys and no incremental tracking.
        # An empty query_based_connector_config (no cursor_columns) means the
        # connector has no high-water mark, and the job task sets
        # full_refresh=True so each run truncates and re-reads the whole table.
        table_spec["table_configuration"] = {"query_based_connector_config": {}}
    else:
        table_spec["table_configuration"] = {
            "primary_keys": split_list(table["primary_keys"]),
            "query_based_connector_config": {"cursor_columns": split_list(table["cursor_columns"])},
        }
    return {"table": table_spec}


def _resolve_node_type(cluster_id: str) -> str:
    """Look up the node_type_id of an existing cluster by its cluster ID."""
    from databricks.sdk import WorkspaceClient
    w = WorkspaceClient()
    cluster = w.clusters.get(cluster_id)
    return cluster.node_type_id


def _cluster_block(pipeline: dict) -> dict:
    """Return a clusters config when serverless is false and compute is set.

    `compute` holds a classic cluster ID (e.g. '0806-070937-2x1z7ueq').
    We resolve the cluster's node_type_id at generation time so the
    pipeline creates a DLT-managed cluster with matching instance types.
    """
    if is_true(pipeline["serverless"]):
        return {}
    compute = (pipeline.get("compute") or "").strip()
    if not compute:
        return {}
    node_type = _resolve_node_type(compute)
    return {"clusters": [{"label": "default", "node_type_id": node_type, "driver_node_type_id": node_type, "num_workers": 1}]}


def ingest_pipeline_entry(pipeline: dict, tables: list[dict], variable_names: set[str] | None = None) -> dict:
    # Direct publishing mode (used by ingestion_definition pipelines) requires
    # a top-level `catalog`/`schema` even though every object below also
    # self-qualifies its own destination_catalog/destination_schema.
    vn = variable_names or set()
    entry = {
        "name": pipeline["pipeline_name"],
        "catalog": _resolve_value(tables[0]["target_catalog"], "target_catalog", vn),
        "schema": _resolve_value(tables[0]["bronze_raw_schema"], "bronze_raw_schema", vn),
        "channel": pipeline["channel"],
        "serverless": is_true(pipeline["serverless"]),
        "ingestion_definition": {
            "ingest_from_uc_foreign_catalog": True,
            "objects": [table_object_entry(table, variable_names) for table in tables],
        },
    }
    entry.update(_cluster_block(pipeline))
    return entry


def etl_pipeline_entry(pipeline: dict, sql_path: str, variable_names: set[str] | None = None) -> dict:
    vn = variable_names or set()
    entry = {
        "name": pipeline["pipeline_name"],
        "catalog": _resolve_value(pipeline["target_catalog"], "target_catalog", vn),
        "schema": _resolve_value(pipeline["bronze_qualified_schema"], "bronze_qualified_schema", vn),
        "channel": pipeline["channel"],
        "serverless": is_true(pipeline["serverless"]),
        "photon": True,
        "libraries": [{"file": {"path": sql_path}}],
    }
    entry.update(_cluster_block(pipeline))
    return entry


def render_etl_pipeline(
    pipeline: dict, sql_source_dir: Path, bundle_root_dir: Path,
    variable_names: set[str] | None = None,
) -> dict:
    """Copy the SQL source file into the bundle directory so it's inside the
    sync root, then return the pipeline entry with a relative path."""
    sql_src = sql_source_dir / pipeline["sql_path"]
    if not sql_src.exists():
        raise FileNotFoundError(
            f"pipeline '{pipeline['pipeline_name']}': sql_path '{pipeline['sql_path']}' "
            f"not found in {sql_source_dir}"
        )
    # Copy SQL into the bundle so it's within the sync root
    dest_dir = bundle_root_dir / "transformations" / "bronze_qualified"
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest_file = dest_dir / pipeline["sql_path"]
    shutil.copy2(sql_src, dest_file)

    return etl_pipeline_entry(pipeline, relative_posix_path(bundle_root_dir, dest_file), variable_names)


def render_job(job: dict, job_pipelines: list[dict], full_replace_pipelines: set[str] | None = None) -> dict:
    job_name = job["job_name"]
    entry: dict = {"name": job_name}

    cron_expression = job.get("cron_expression", "").strip()
    if cron_expression:
        entry["schedule"] = {
            "quartz_cron_expression": cron_expression,
            "timezone_id": job.get("timezone_id", "").strip() or "UTC",
            "pause_status": job.get("status", "").strip() or "UNPAUSED",
        }

    tasks = []
    for pipeline in job_pipelines:
        pipeline_name = pipeline["pipeline_name"]
        task = {"task_key": pipeline_name}
        depends_on = split_list(pipeline.get("depends_on", ""))
        if depends_on:
            task["depends_on"] = [{"task_key": name} for name in depends_on]
        pipeline_task = {"pipeline_id": f"${{resources.pipelines.{pipeline_name}.id}}"}
        if full_replace_pipelines and pipeline_name in full_replace_pipelines:
            # Full refresh truncates the destination tables and re-ingests the
            # whole source, so each run replaces the table contents.
            pipeline_task["full_refresh"] = True
        task["pipeline_task"] = pipeline_task
        tasks.append(task)
    entry["tasks"] = tasks
    return entry


def generate(config: dict | None = None) -> list[Path]:
    """Read configuration tables from Unity Catalog, validate, and write
    a self-contained databricks.yml per domain into the bundle output root.
    Returns the list of generated bundle root directories."""
    if config is None:
        config = load_config()

    catalog = config["catalog"]
    schema = config["schema"]
    targets = config.get("targets")  # None if not specified
    bundle_output_root = Path(config["bundle_output_root"])
    sql_source_dir = Path(config["sql_source_dir"])
    domain_override = config.get("domain")  # None or a string

    # --- Load from Unity Catalog tables -----------------------------------
    domains = load_table(catalog, schema, "bundle_domains")
    jobs = load_table(catalog, schema, "jobs")
    pipelines = load_table(catalog, schema, "pipelines")
    tables = load_table(catalog, schema, "tables")

    # --- Load bundle variables (optional) ---------------------------------
    variables_def, target_variables = load_variables(catalog, schema)
    variable_names = set(variables_def) if variables_def else set()
    if targets and target_variables:
        for target_name, target_config in targets.items():
            if target_name in target_variables:
                target_config["variables"] = target_variables[target_name]

    # --- Validation -------------------------------------------------------
    require_unique(domains, lambda d: d["domain_name"], "bundle_domains", "domain_name")
    domain_names = {d["domain_name"] for d in domains}
    bundle_name_by_domain = {
        d["domain_name"]: d.get("bundle_name", "").strip() or f"{d['domain_name']}"
        for d in domains
    }

    if domain_override is not None and domain_override not in domain_names:
        raise ValueError(
            f"domain '{domain_override}' not found in {catalog}.{schema}.bundle_domains "
            f"(known: {sorted(domain_names)})"
        )
    domains_to_build = [d for d in domains if domain_override is None or d["domain_name"] == domain_override]

    for job in jobs:
        status = job.get("status", "").strip()
        if status and status not in ("UNPAUSED", "PAUSED"):
            raise ValueError(
                f"jobs: job '{job['job_name']}' has invalid status "
                f"'{status}' (must be UNPAUSED or PAUSED)"
            )
    for pipeline in pipelines:
        if pipeline["type"] not in ("ingest", "etl"):
            raise ValueError(
                f"pipelines: pipeline '{pipeline['pipeline_name']}' has invalid type "
                f"'{pipeline['type']}' (must be 'ingest' or 'etl')"
            )
        if not is_true(pipeline["serverless"]) and not (pipeline.get("compute") or "").strip():
            raise ValueError(
                f"pipelines: pipeline '{pipeline['pipeline_name']}' has serverless=false "
                f"but no compute cluster ID specified"
            )

    require_fk(
        jobs, lambda j: j.get("domain_name", "").strip(), domain_names,
        lambda j: f"jobs: job '{j['job_name']}'", "domain_name", hint="bundle_domains",
    )
    require_fk(
        pipelines, lambda p: p.get("domain_name", "").strip(), domain_names,
        lambda p: f"pipelines: pipeline '{p['pipeline_name']}'", "domain_name", hint="bundle_domains",
    )

    require_unique(jobs, lambda j: j["job_name"], "jobs", "job_name")
    require_unique(pipelines, lambda p: p["pipeline_name"], "pipelines", "pipeline_name")
    require_unique(tables, lambda t: (t["pipeline_name"], destination_table_for(t)), "tables", "pipeline_name+destination_table")

    job_names = {j["job_name"] for j in jobs}
    pipelines_by_name = {p["pipeline_name"]: p for p in pipelines}

    ingest_pipelines = {p["pipeline_name"]: p for p in pipelines if p["type"] == "ingest"}
    etl_pipelines = {p["pipeline_name"]: p for p in pipelines if p["type"] == "etl"}
    full_replace_pipelines: set[str] = set()

    tables_by_pipeline: dict[str, list[dict]] = defaultdict(list)
    for table in tables:
        tables_by_pipeline[table["pipeline_name"]].append(table)

    for table in tables:
        if table["pipeline_name"] not in ingest_pipelines:
            raise ValueError(
                f"tables: table '{table['source_table']}' references pipeline_name "
                f"'{table['pipeline_name']}', which must be a pipeline with type='ingest' in pipelines"
            )
        # primary_keys and cursor_columns go together: both set = incremental
        # merge ingestion, both empty = full replace. One without the other is
        # not a valid managed-ingestion configuration.
        has_primary_keys = bool(split_list(table.get("primary_keys", "")))
        has_cursor_columns = bool(split_list(table.get("cursor_columns", "")))
        if has_primary_keys != has_cursor_columns:
            missing = "cursor_columns" if has_primary_keys else "primary_keys"
            raise ValueError(
                f"tables: table '{table['source_table']}' (pipeline "
                f"'{table['pipeline_name']}') is missing {missing} — set both "
                f"primary_keys and cursor_columns for incremental ingestion, or "
                f"leave both empty for full replace"
            )

    for pipeline in ingest_pipelines.values():
        pipeline_tables = tables_by_pipeline[pipeline["pipeline_name"]]
        if not pipeline_tables:
            raise ValueError(
                f"pipelines: ingest pipeline '{pipeline['pipeline_name']}' has no rows "
                f"in tables referencing it"
            )
        target_catalogs = {t["target_catalog"] for t in pipeline_tables}
        if len(target_catalogs) > 1:
            raise ValueError(
                f"tables: ingest pipeline '{pipeline['pipeline_name']}' has rows with "
                f"different target_catalog values ({sorted(target_catalogs)}) — direct "
                f"publishing mode requires one catalog per pipeline"
            )
        bronze_raw_schemas = {t["bronze_raw_schema"] for t in pipeline_tables}
        if len(bronze_raw_schemas) > 1:
            raise ValueError(
                f"tables: ingest pipeline '{pipeline['pipeline_name']}' has rows with "
                f"different bronze_raw_schema values ({sorted(bronze_raw_schemas)}) — direct "
                f"publishing mode requires one schema per pipeline"
            )
        # Full refresh is requested per task, i.e. for the whole pipeline, so a
        # pipeline can't mix full-replace tables with incremental ones.
        if all(is_full_replace(t) for t in pipeline_tables):
            full_replace_pipelines.add(pipeline["pipeline_name"])
        if len({is_full_replace(t) for t in pipeline_tables}) > 1:
            full_replace_tables = sorted(t["source_table"] for t in pipeline_tables if is_full_replace(t))
            raise ValueError(
                f"tables: ingest pipeline '{pipeline['pipeline_name']}' mixes full-replace "
                f"tables ({full_replace_tables}) with incremental ones — full refresh applies "
                f"to the whole pipeline, so move them into a separate ingest pipeline"
            )

    for pipeline in etl_pipelines.values():
        if not pipeline.get("sql_path", "").strip():
            raise ValueError(
                f"pipelines: ETL pipeline '{pipeline['pipeline_name']}' has no sql_path"
            )

    require_fk(
        pipelines, lambda p: p.get("job_name", "").strip(), job_names,
        lambda p: f"pipelines: pipeline '{p['pipeline_name']}'", "job_name", hint="jobs",
    )
    task_job_by_pipeline = {p["pipeline_name"]: p["job_name"] for p in pipelines}

    # `depends_on` must reference a pipeline that's also scheduled in the
    # same job — a task can only depend on another task within that job.
    for pipeline in pipelines:
        pipeline_job = task_job_by_pipeline[pipeline["pipeline_name"]]
        for dep_name in split_list(pipeline.get("depends_on", "")):
            if dep_name not in pipelines_by_name:
                raise ValueError(
                    f"pipelines: pipeline '{pipeline['pipeline_name']}' (job "
                    f"'{pipeline_job}') depends_on unknown pipeline '{dep_name}'"
                )
            dep_job = task_job_by_pipeline.get(dep_name)
            if dep_job != pipeline_job:
                raise ValueError(
                    f"pipelines: pipeline '{pipeline['pipeline_name']}' (job "
                    f"'{pipeline_job}') depends_on '{dep_name}', which is not a task "
                    f"in that same job"
                )

    # A pipeline's job must belong to the same domain — a job can only
    # schedule pipelines that live in its own domain's bundle.
    job_domain_by_name = {j["job_name"]: j["domain_name"] for j in jobs}
    for pipeline in pipelines:
        job_domain = job_domain_by_name[pipeline["job_name"]]
        pipeline_domain = pipeline["domain_name"]
        if job_domain != pipeline_domain:
            raise ValueError(
                f"pipelines: pipeline '{pipeline['pipeline_name']}' (domain "
                f"'{pipeline_domain}') is scheduled under job '{pipeline['job_name']}' "
                f"(domain '{job_domain}') — a job can only run pipelines from its own domain"
            )

    # --- Generate per-domain bundles --------------------------------------
    generated_bundle_dirs: list[Path] = []

    for domain in domains_to_build:
        domain_name = domain["domain_name"]
        bundle_name = bundle_name_by_domain[domain_name]

        domain_jobs = [j for j in jobs if j["domain_name"] == domain_name]
        domain_pipelines = [p for p in pipelines if p["domain_name"] == domain_name]
        domain_pipeline_names = {p["pipeline_name"] for p in domain_pipelines}
        domain_tables = [t for t in tables if t["pipeline_name"] in domain_pipeline_names]

        domain_ingest_pipelines = {p["pipeline_name"]: p for p in domain_pipelines if p["type"] == "ingest"}
        domain_etl_pipelines = {p["pipeline_name"]: p for p in domain_pipelines if p["type"] == "etl"}
        domain_tables_by_pipeline: dict[str, list[dict]] = defaultdict(list)
        for table in domain_tables:
            domain_tables_by_pipeline[table["pipeline_name"]].append(table)

        # Each domain gets its own isolated bundle directory
        domain_bundle_root_dir = bundle_output_root / domain_name

        pipeline_entry_by_name: dict[str, dict] = {}
        for pipeline_name, pipeline in domain_ingest_pipelines.items():
            pipeline_entry_by_name[pipeline_name] = ingest_pipeline_entry(
                pipeline, domain_tables_by_pipeline[pipeline_name], variable_names
            )
        for pipeline_name, pipeline in domain_etl_pipelines.items():
            pipeline_entry_by_name[pipeline_name] = render_etl_pipeline(
                pipeline, sql_source_dir, domain_bundle_root_dir, variable_names
            )
        pipeline_entries = {p["pipeline_name"]: pipeline_entry_by_name[p["pipeline_name"]] for p in domain_pipelines}

        domain_pipelines_by_job: dict[str, list[dict]] = defaultdict(list)
        for pipeline in domain_pipelines:
            domain_pipelines_by_job[pipeline["job_name"]].append(pipeline)
        job_entries = {
            job["job_name"]: render_job(
                job, domain_pipelines_by_job[job["job_name"]], full_replace_pipelines
            )
            for job in domain_jobs
        }

        render_databricks_yml(
            domain_name, bundle_name, job_entries, pipeline_entries,
            domain_bundle_root_dir, catalog, schema, targets, variables_def,
        )

        print(f"Domain '{domain_name}' ({bundle_name}): generated {len(domain_jobs)} job(s), "
              f"{len(domain_ingest_pipelines)} ingest pipeline(s), {len(domain_etl_pipelines)} ETL pipeline(s), "
              f"{len(domain_tables)} table(s) -> {domain_bundle_root_dir / 'databricks.yml'}")
        for job in domain_jobs:
            print(f"  - {job['job_name']}:")
            for pipeline in domain_pipelines_by_job[job["job_name"]]:
                pipeline_name = pipeline["pipeline_name"]
                deps = split_list(pipeline.get("depends_on", ""))
                dep_note = f" (depends_on: {', '.join(deps)})" if deps else ""
                if pipeline_name in domain_ingest_pipelines:
                    mode = "full replace" if pipeline_name in full_replace_pipelines else "incremental"
                    print(f"      ingest pipeline {pipeline_name}{dep_note} [{mode}]:")
                    for table in domain_tables_by_pipeline[pipeline_name]:
                        print(f"        {table['source_catalog']}.{table['source_schema']}.{table['source_table']} "
                              f"-> {table['target_catalog']}.{table['bronze_raw_schema']}.{destination_table_for(table)}")
                else:
                    pipeline = domain_etl_pipelines[pipeline_name]
                    print(f"      etl pipeline {pipeline_name}{dep_note}: "
                          f"runs {pipeline['sql_path']} -> {pipeline['target_catalog']}.{pipeline['bronze_qualified_schema']}")

        generated_bundle_dirs.append(domain_bundle_root_dir)

    return generated_bundle_dirs


def main() -> None:
    """Entry point — loads generator_config.yaml and generates all bundles."""
    generate()


if __name__ == "__main__":
    main()
