from __future__ import annotations

import argparse
import shutil
from collections import defaultdict
from pathlib import Path

from common import (
    deploy_bundle,
    dump_yaml,
    is_true,
    load_csv,
    load_targets,
    relative_posix_path,
    require_fk,
    require_unique,
    split_list,
    write_yaml_resource,
)

ROOT = Path(__file__).resolve().parent.parent


DATABRICKS_YML_HEADER_TEMPLATE = """# AUTO-GENERATED by generator/generate_bundles.py — do not edit by hand.
# This file is a single, self-contained bundle definition for the
# '{domain_name}' domain (see config/bundle_domains.csv): every resource
# from jobs.csv/pipelines.csv/tables.csv belonging to this
# domain is inlined below (no `include:` needed). The per-resource files
# under resources/ hold the exact same content, split out for a
# human-readable, hierarchical view — they aren't referenced from here.
# Catalogs/schemas are NOT here — see bundles/platform/databricks.yml,
# generated separately by generate_platform_bundle.py.
"""


def render_databricks_yml(
    domain_name: str,
    bundle_name: str,
    job_entries: dict[str, dict],
    pipeline_entries: dict[str, dict],
    bundle_root_dir: Path,
    targets: dict,
) -> None:
    """Aggregate the chosen domain's resource entries into its own
    self-contained databricks.yml under bundle_root_dir (the project root by
    default), alongside the source folders it references (e.g.
    transformations/), not inside the generated build/ output."""
    header = DATABRICKS_YML_HEADER_TEMPLATE.format(domain_name=domain_name, bundle_name=bundle_name)
    bundle = {
        "bundle": {"name": bundle_name},
        "resources": {"jobs": job_entries, "pipelines": pipeline_entries},
        "targets": targets,
    }
    bundle_root_dir.mkdir(parents=True, exist_ok=True)
    (bundle_root_dir / "databricks.yml").write_text(header + dump_yaml(bundle), encoding="utf-8")


def destination_table_for(table: dict) -> str:
    return table.get("destination_table", "").strip() or table["source_table"]


def ingest_pipeline_dir_for(out_dir: Path, job_name: str, pipeline_name: str) -> Path:
    return out_dir / "resources" / "jobs" / job_name / "pipelines" / "ingest" / pipeline_name


def etl_pipeline_dir_for(out_dir: Path, job_name: str, pipeline_name: str) -> Path:
    return out_dir / "resources" / "jobs" / job_name / "pipelines" / "etl" / pipeline_name


def table_object_entry(table: dict) -> dict:
    return {
        "table": {
            "destination_catalog": table["target_catalog"],
            "destination_schema": table["bronze_raw_schema"],
            "destination_table": destination_table_for(table),
            "source_catalog": table["source_catalog"],
            "source_schema": table["source_schema"],
            "source_table": table["source_table"],
            "table_configuration": {
                "primary_keys": split_list(table["primary_keys"]),
                "query_based_connector_config": {"cursor_columns": split_list(table["cursor_columns"])},
            },
        }
    }


def ingest_pipeline_entry(pipeline: dict, tables: list[dict]) -> dict:
    # Direct publishing mode (used by ingestion_definition pipelines) requires
    # a top-level `catalog`/`schema` even though every object below also
    # self-qualifies its own destination_catalog/destination_schema.
    return {
        "name": pipeline["pipeline_name"],
        "catalog": tables[0]["target_catalog"],
        "schema": tables[0]["bronze_raw_schema"],
        "channel": pipeline["channel"],
        "serverless": is_true(pipeline["serverless"]),
        "ingestion_definition": {
            "ingest_from_uc_foreign_catalog": True,
            "objects": [table_object_entry(table) for table in tables],
        },
    }


def render_ingest_pipeline(pipeline: dict, tables: list[dict], job_name: str, out_dir: Path) -> dict:
    entry = ingest_pipeline_entry(pipeline, tables)
    pipeline_dir = ingest_pipeline_dir_for(out_dir, job_name, pipeline["pipeline_name"])
    write_yaml_resource(
        pipeline_dir / f"{pipeline['pipeline_name']}.pipeline.yml", "pipelines", pipeline["pipeline_name"], entry
    )
    return entry


def etl_pipeline_entry(pipeline: dict, sql_path: str) -> dict:
    return {
        "name": pipeline["pipeline_name"],
        "catalog": pipeline["target_catalog"],
        "schema": pipeline["bronze_qualified_schema"],
        "channel": pipeline["channel"],
        "serverless": is_true(pipeline["serverless"]),
        "photon": True,
        "libraries": [{"file": {"path": sql_path}}],
    }


def render_etl_pipeline(
    pipeline: dict, job_name: str, out_dir: Path, sql_source_dir: Path, bundle_root_dir: Path
) -> dict:
    """Writes the pipeline's own file (its `sql_path` relative to a COPY of
    the SQL under out_dir/transformations/) and returns a SEPARATE entry for
    the aggregated databricks.yml at bundle_root_dir, whose `sql_path` points
    directly at the ORIGINAL source file — never the same entry reused for
    both, since `sql_path` is relative to wherever the entry ends up living."""
    pipeline_dir = etl_pipeline_dir_for(out_dir, job_name, pipeline["pipeline_name"])

    qualify_dir = out_dir / "transformations" / "bronze_qualified"
    qualify_dir.mkdir(parents=True, exist_ok=True)

    sql_src = sql_source_dir / pipeline["sql_path"]
    if not sql_src.exists():
        raise FileNotFoundError(
            f"pipeline '{pipeline['pipeline_name']}': sql_path '{pipeline['sql_path']}' "
            f"not found in {sql_source_dir}"
        )
    dest_file = qualify_dir / pipeline["sql_path"]
    shutil.copy(sql_src, dest_file)

    file_entry = etl_pipeline_entry(pipeline, relative_posix_path(pipeline_dir, dest_file))
    write_yaml_resource(
        pipeline_dir / f"{pipeline['pipeline_name']}.pipeline.yml", "pipelines", pipeline["pipeline_name"], file_entry
    )

    return etl_pipeline_entry(pipeline, relative_posix_path(bundle_root_dir, sql_src))


def render_job(job: dict, job_pipelines: list[dict], out_dir: Path) -> dict:
    job_name = job["job_name"]
    entry: dict = {"name": job_name}

    cron_expression = job.get("cron_expression", "").strip()
    if cron_expression:
        entry["schedule"] = {
            "quartz_cron_expression": cron_expression,
            "timezone_id": job.get("timezone_id", "").strip() or "UTC",
            "pause_status": job.get("status", "").strip() or "UNPAUSED",
        }

    tasks = []
    for pipeline in job_pipelines:
        pipeline_name = pipeline["pipeline_name"]
        task = {"task_key": pipeline_name}
        depends_on = split_list(pipeline.get("depends_on", ""))
        if depends_on:
            task["depends_on"] = [{"task_key": name} for name in depends_on]
        task["pipeline_task"] = {"pipeline_id": f"${{resources.pipelines.{pipeline_name}.id}}"}
        tasks.append(task)
    entry["tasks"] = tasks

    job_dir = out_dir / "resources" / "jobs" / job_name
    write_yaml_resource(job_dir / f"{job_name}.job.yml", "jobs", job_name, entry)
    return entry


def generate(
    config_dir: Path,
    out_dir: Path,
    sql_source_dir: Path,
    bundle_root_dir: Path,
    workspaces_config: Path,
    domain_override: str | None = None,
    target: str = "dev",
    deploy: bool = True,
    profile: str | None = None,
) -> None:
    targets = load_targets(workspaces_config)
    domains = load_csv(config_dir / "bundle_domains.csv")
    jobs = load_csv(config_dir / "jobs.csv")
    pipelines = load_csv(config_dir / "pipelines.csv")
    tables = load_csv(config_dir / "tables.csv")

    require_unique(domains, lambda d: d["domain_name"], "bundle_domains.csv", "domain_name")
    domain_names = {d["domain_name"] for d in domains}
    bundle_name_by_domain = {
        d["domain_name"]: d.get("bundle_name", "").strip() or f"shiba_{d['domain_name']}"
        for d in domains
    }

    if domain_override is not None and domain_override not in domain_names:
        raise ValueError(
            f"domain '{domain_override}' not found in bundle_domains.csv "
            f"(known: {sorted(domain_names)})"
        )
    # With no --domain, every domain in bundle_domains.csv is built and
    # (unless --no-deploy) deployed, one at a time, in CSV row order.
    domains_to_build = [d for d in domains if domain_override is None or d["domain_name"] == domain_override]

    for job in jobs:
        status = job.get("status", "").strip()
        if status and status not in ("UNPAUSED", "PAUSED"):
            raise ValueError(
                f"jobs.csv: job '{job['job_name']}' has invalid status "
                f"'{status}' (must be UNPAUSED or PAUSED)"
            )
    for pipeline in pipelines:
        if pipeline["type"] not in ("ingest", "etl"):
            raise ValueError(
                f"pipelines.csv: pipeline '{pipeline['pipeline_name']}' has invalid type "
                f"'{pipeline['type']}' (must be 'ingest' or 'etl')"
            )

    require_fk(
        jobs, lambda j: j.get("domain_name", "").strip(), domain_names,
        lambda j: f"jobs.csv: job '{j['job_name']}'", "domain_name", hint="bundle_domains.csv",
    )
    require_fk(
        pipelines, lambda p: p.get("domain_name", "").strip(), domain_names,
        lambda p: f"pipelines.csv: pipeline '{p['pipeline_name']}'", "domain_name", hint="bundle_domains.csv",
    )

    require_unique(jobs, lambda j: j["job_name"], "jobs.csv", "job_name")
    require_unique(pipelines, lambda p: p["pipeline_name"], "pipelines.csv", "pipeline_name")
    require_unique(tables, lambda t: (t["pipeline_name"], destination_table_for(t)), "tables.csv", "pipeline_name+destination_table")

    job_names = {j["job_name"] for j in jobs}
    pipelines_by_name = {p["pipeline_name"]: p for p in pipelines}

    ingest_pipelines = {p["pipeline_name"]: p for p in pipelines if p["type"] == "ingest"}
    etl_pipelines = {p["pipeline_name"]: p for p in pipelines if p["type"] == "etl"}

    tables_by_pipeline: dict[str, list[dict]] = defaultdict(list)
    for table in tables:
        tables_by_pipeline[table["pipeline_name"]].append(table)

    for table in tables:
        if table["pipeline_name"] not in ingest_pipelines:
            raise ValueError(
                f"tables.csv: table '{table['source_table']}' references pipeline_name "
                f"'{table['pipeline_name']}', which must be a pipeline with type='ingest' in pipelines.csv"
            )

    for pipeline in ingest_pipelines.values():
        pipeline_tables = tables_by_pipeline[pipeline["pipeline_name"]]
        if not pipeline_tables:
            raise ValueError(
                f"pipelines.csv: ingest pipeline '{pipeline['pipeline_name']}' has no rows "
                f"in tables.csv referencing it"
            )
        target_catalogs = {t["target_catalog"] for t in pipeline_tables}
        if len(target_catalogs) > 1:
            raise ValueError(
                f"tables.csv: ingest pipeline '{pipeline['pipeline_name']}' has rows with "
                f"different target_catalog values ({sorted(target_catalogs)}) — direct "
                f"publishing mode requires one catalog per pipeline"
            )
        bronze_raw_schemas = {t["bronze_raw_schema"] for t in pipeline_tables}
        if len(bronze_raw_schemas) > 1:
            raise ValueError(
                f"tables.csv: ingest pipeline '{pipeline['pipeline_name']}' has rows with "
                f"different bronze_raw_schema values ({sorted(bronze_raw_schemas)}) — direct "
                f"publishing mode requires one schema per pipeline"
            )

    for pipeline in etl_pipelines.values():
        if not pipeline.get("sql_path", "").strip():
            raise ValueError(
                f"pipelines.csv: ETL pipeline '{pipeline['pipeline_name']}' has no sql_path"
            )

    require_fk(
        pipelines, lambda p: p.get("job_name", "").strip(), job_names,
        lambda p: f"pipelines.csv: pipeline '{p['pipeline_name']}'", "job_name", hint="jobs.csv",
    )
    task_job_by_pipeline = {p["pipeline_name"]: p["job_name"] for p in pipelines}

    # `depends_on` must reference a pipeline that's also scheduled in the
    # same job — a task can only depend on another task within that job.
    for pipeline in pipelines:
        pipeline_job = task_job_by_pipeline[pipeline["pipeline_name"]]
        for dep_name in split_list(pipeline.get("depends_on", "")):
            if dep_name not in pipelines_by_name:
                raise ValueError(
                    f"pipelines.csv: pipeline '{pipeline['pipeline_name']}' (job "
                    f"'{pipeline_job}') depends_on unknown pipeline '{dep_name}'"
                )
            dep_job = task_job_by_pipeline.get(dep_name)
            if dep_job != pipeline_job:
                raise ValueError(
                    f"pipelines.csv: pipeline '{pipeline['pipeline_name']}' (job "
                    f"'{pipeline_job}') depends_on '{dep_name}', which is not a task "
                    f"in that same job"
                )

    # A pipeline's job must belong to the same domain — a job can only
    # schedule pipelines that live in its own domain's bundle.
    job_domain_by_name = {j["job_name"]: j["domain_name"] for j in jobs}
    for pipeline in pipelines:
        job_domain = job_domain_by_name[pipeline["job_name"]]
        pipeline_domain = pipeline["domain_name"]
        if job_domain != pipeline_domain:
            raise ValueError(
                f"pipelines.csv: pipeline '{pipeline['pipeline_name']}' (domain "
                f"'{pipeline_domain}') is scheduled under job '{pipeline['job_name']}' "
                f"(domain '{job_domain}') — a job can only run pipelines from its own domain"
            )

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for domain in domains_to_build:
        domain_name = domain["domain_name"]
        bundle_name = bundle_name_by_domain[domain_name]

        domain_jobs = [j for j in jobs if j["domain_name"] == domain_name]
        domain_pipelines = [p for p in pipelines if p["domain_name"] == domain_name]
        domain_pipeline_names = {p["pipeline_name"] for p in domain_pipelines}
        domain_tables = [t for t in tables if t["pipeline_name"] in domain_pipeline_names]

        domain_ingest_pipelines = {p["pipeline_name"]: p for p in domain_pipelines if p["type"] == "ingest"}
        domain_etl_pipelines = {p["pipeline_name"]: p for p in domain_pipelines if p["type"] == "etl"}
        domain_tables_by_pipeline: dict[str, list[dict]] = defaultdict(list)
        for table in domain_tables:
            domain_tables_by_pipeline[table["pipeline_name"]].append(table)

        domain_out_dir = out_dir / domain_name
        domain_out_dir.mkdir(parents=True, exist_ok=True)
        domain_bundle_root_dir = bundle_root_dir

        # Rendered in two passes (ingest pipelines, then ETL), which don't
        # preserve pipelines.csv's original row order on their own — reindex
        # by that order here so the aggregated databricks.yml lists pipelines
        # the same way the CSV does.
        pipeline_entry_by_name: dict[str, dict] = {}
        for pipeline_name, pipeline in domain_ingest_pipelines.items():
            pipeline_entry_by_name[pipeline_name] = render_ingest_pipeline(
                pipeline, domain_tables_by_pipeline[pipeline_name], task_job_by_pipeline[pipeline_name], domain_out_dir
            )
        for pipeline_name, pipeline in domain_etl_pipelines.items():
            pipeline_entry_by_name[pipeline_name] = render_etl_pipeline(
                pipeline, task_job_by_pipeline[pipeline_name], domain_out_dir, sql_source_dir, domain_bundle_root_dir
            )
        pipeline_entries = {p["pipeline_name"]: pipeline_entry_by_name[p["pipeline_name"]] for p in domain_pipelines}

        domain_pipelines_by_job: dict[str, list[dict]] = defaultdict(list)
        for pipeline in domain_pipelines:
            domain_pipelines_by_job[pipeline["job_name"]].append(pipeline)
        job_entries = {
            job["job_name"]: render_job(job, domain_pipelines_by_job[job["job_name"]], domain_out_dir)
            for job in domain_jobs
        }

        render_databricks_yml(domain_name, bundle_name, job_entries, pipeline_entries, domain_bundle_root_dir, targets)

        print(f"Domain '{domain_name}' ({bundle_name}): generated {len(domain_jobs)} job(s), "
              f"{len(domain_ingest_pipelines)} ingest pipeline(s), {len(domain_etl_pipelines)} ETL pipeline(s), "
              f"{len(domain_tables)} table(s) -> {domain_bundle_root_dir / 'databricks.yml'}")
        for job in domain_jobs:
            print(f"  - {job['job_name']}:")
            for pipeline in domain_pipelines_by_job[job["job_name"]]:
                pipeline_name = pipeline["pipeline_name"]
                deps = split_list(pipeline.get("depends_on", ""))
                dep_note = f" (depends_on: {', '.join(deps)})" if deps else ""
                if pipeline_name in domain_ingest_pipelines:
                    print(f"      ingest pipeline {pipeline_name}{dep_note}:")
                    for table in domain_tables_by_pipeline[pipeline_name]:
                        print(f"        {table['source_catalog']}.{table['source_schema']}.{table['source_table']} "
                              f"-> {table['target_catalog']}.{table['bronze_raw_schema']}.{destination_table_for(table)}")
                else:
                    pipeline = domain_etl_pipelines[pipeline_name]
                    print(f"      etl pipeline {pipeline_name}{dep_note}: "
                          f"runs {pipeline['sql_path']} -> {pipeline['target_catalog']}.{pipeline['bronze_qualified_schema']}")

        if deploy:
            print(f"  Deploying '{bundle_name}' (target '{target}') from {domain_bundle_root_dir} ...")
            deploy_bundle(domain_bundle_root_dir, target, profile)
            print(f"  Deployed '{bundle_name}'.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config-dir", default=str(ROOT / "config"))
    parser.add_argument("--sql-source", default=str(ROOT / "transformations" / "bronze_qualified"))
    parser.add_argument("--out", default=str(ROOT / "build"))
    parser.add_argument(
        "--workspaces-config",
        default=str(ROOT / "workspaces.yaml"),
        help="YAML file with default_domain, and dev/prod workspace host + prod run_as_user for the targets: block.",
    )
    parser.add_argument(
        "--domain",
        default=None,
        help="Restrict to one row of bundle_domains.csv. Default: build and deploy "
        "every domain in bundle_domains.csv, one at a time.",
    )
    parser.add_argument(
        "--bundle-root",
        default=str(ROOT),
        help="Directory each domain's aggregated, self-contained databricks.yml "
        "is written to directly (default: project root, alongside "
        "transformations/ and config/). Each domain overwrites the same file "
        "here in turn, so it's generated and (unless --no-deploy) deployed "
        "before the next domain is written.",
    )
    parser.add_argument(
        "--target",
        default="dev",
        choices=["dev", "prod"],
        help="Which targets: entry (from workspaces.yaml) to validate/deploy each domain against (default: dev).",
    )
    parser.add_argument(
        "--no-deploy",
        dest="deploy",
        action="store_false",
        help="Only generate each domain's databricks.yml; skip running `databricks bundle validate`/`deploy`.",
    )
    parser.add_argument(
        "--profile",
        default=None,
        help="Databricks CLI profile to pass to `databricks bundle validate`/`deploy` (--profile).",
    )
    args = parser.parse_args()

    generate(
        Path(args.config_dir),
        Path(args.out),
        Path(args.sql_source),
        Path(args.bundle_root),
        Path(args.workspaces_config),
        args.domain,
        args.target,
        args.deploy,
        args.profile,
    )


if __name__ == "__main__":
    main()
